services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: km_todo
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  db-e2e:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: km_todo_e2e_test
    ports:
      - "${DB_E2E_PORT:-5433}:5432"
    volumes:
      - pgdata-e2e:/var/lib/postgresql/data

  app:
    build: .
    command: npm run start
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/km_todo
      NODE_ENV: production
      PORT: ${PORT:-3000}
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    depends_on:
      - db

volumes:
  pgdata:
  pgdata-e2e: 