services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: km_todo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    command: npm run start
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/km_todo
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  pgdata: 